### ISSUE TITLE
Network bulk upload column header "NONE" - Error 500

### ISSUE THREAD

**Issue by sv3nster** [samilliken/openDCIM#1040]
While attempting to omit certain fields from the network bulk upload by selecting "None", I am getting the following error. I figured we should be able to do this, since the none option is available. Thanks!

`[Tue May 22 18:17:15.826348 2018] [:error] [pid 28385] [client 146.91.12.16:60018] PHP Fatal error:  Uncaught exception 'PHPExcel_Exception' with message 'Invalid cell coordinate @2' in /var/www/openDCIM-18.01/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php:590\nStack trace:\n#0 /var/www/openDCIM-18.01/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php(1228): PHPExcel_Cell::coordinateFromString('@2')\n#1 /var/www/openDCIM-18.01/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet.php(1187): PHPExcel_Worksheet->_createNewCell('@2')\n#2 /var/www/openDCIM-18.01/bulk_network.php(159): PHPExcel_Worksheet->getCell('@2')\n#3 {main}\n  thrown in /var/www/openDCIM-18.01/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php on line 590, referer: https://10.0.0.5/bulk_network.php?stage=headers`

**Comment by sv3nster** [comment]
![capture](https://user-images.githubusercontent.com/36329875/40396257-a08a1b4e-5df1-11e8-92f6-65f327e640db.JPG)
